#pragma once

#include "io.h"


DEBUG_PLATFORM_READ_ENTIRE_FILE(DEBUGWin32ReadEntireFile);
DEBUG_PLATFORM_FREE_FILE_MEMORY(DEBUGWin32FreeFileMemory);
DEBUG_PLATFORM_WRITE_ENTIRE_FILE(DEBUGWin32WriteEntireFile);